#to start buying
#set 'sell' here else use 'buy'
previousAction = 'sell'

#candles 
adxOptIn 	= 14
trixOptIn 		= 18
cciOptIn 		= 20
rsiOptIn		= 6

#Initiate buy if all of this happens
buyAdxOver = 30
buyCciUnder = -130
buyPrevRsiUnder = 26
#additional trix uptrending.

#Initiate Sell if all of this happens
sellAdxOver = 30
sellCciOver = 100
#additional trix downtrending

#trailing stop in %
trailSellPercent = 5

#Options are 'enabled' or 'disabled'. 
#sell price must be higher than buy price if enabled.
#not much recommended but possible :)
priceProtection = 'disabled'
