#to start buying
#set 'sell' here else use 'buy'
previousAction = 'sell'

#candles 
adxOptIn 	= 14
trixOptIn 		= 15 #was 18
cciOptIn 		= 20

bbOptInTime		= 10 #was 20
bbOptInStdDevs		= 2

#Initiate buy if all of this happens
buyAdxOver = 30
buyCciUnder = -130
trixBuyTrigger = -3 #set -100 to disable
#less than trixBuytrigger
#or trix uptrending.

#Initiate Sell if all of this happens
sellAdxOver = 30
sellCciOver = 110 #default 100
#additional trix downtrending

#Pump and Dump settings
#Pumpdetect x * 100%
#set to 100000000 to disable
pumpVolGain = 30 #10-100 works nice
pdTimeout = 200 #candles for timeout


#Options are 'enabled' or 'disabled'. 
#sell price must be higher than buy price if enabled.
#not much recommended but possible :)
priceProtection = 'disabled'

